name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      # There's no actual PHP or JS, despite having phpcs.xml and package.json files.
      phplinting: false
      js: false
